amp/sandbox/urls.py
from django.conf.urls import url, patterns, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
import views


api_urlpatterns = patterns('',
    url(r'^sandbox', views.SandboxAPICreateView.as_view(), name="api-create-sandbox"),
    url(r'^vm', views.VMAPIDetail.as_view(), name="api-get-vm"),
)

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=login_required(views.SandboxListView.as_view()),
        name='list_sandboxes'
    ),
    url(
        regex=r'create',
        view=login_required(views.SandboxCreateView.as_view()),
        name='create'
    ),
    url(r'^api/', include(api_urlpatterns))
]

amp/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [

    url(r'', include("amp.sandbox.urls", namespace="sandbox")),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("amp.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request),
        url(r'^403/$', default_views.permission_denied),
        url(r'^404/$', default_views.page_not_found),
        url(r'^500/$', default_views.server_error),
    ]

amp/sandbox/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
# Create your models here.


class VM(models.Model):
    MANAGE_NODE, DATABASE, ENDPOINT = ("manage", 'database', "endpoint")
    VM_ROLES = (
        (MANAGE_NODE, "Manage Node"),
        (DATABASE, "Database"),
        (ENDPOINT, "Endpoint")
    )
    hostname = models.CharField(blank=False, max_length=120)
    ip_address = models.GenericIPAddressField(blank=False)
    sandbox = models.ForeignKey('Sandbox', blank=False, related_name="vms")
    role = models.CharField(choices=VM_ROLES, max_length=30)
    login = models.CharField(blank=False, max_length=30)
    password = models.CharField(blank=True, max_length=30)

    def __unicode__(self):
        return "VM %s %s" %(self.hostname, self.role)


class Sandbox(models.Model):

    READY, INSTALLING, STOPPED, DESTROYED = ("ready", "installing", "stopped", "destroyed")
    SANDBOX_STATUSES = (
        (READY, "READY"),
        (INSTALLING, "INSTALLING"),
        (STOPPED, "STOPPED"),
        (DESTROYED, "DESTROYED")
    )
    name = models.CharField(max_length=90, blank=True, default="NoName")
    template = models.ForeignKey('Template', related_name="sandboxes")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="sandboxes")
    status = models.CharField(choices=SANDBOX_STATUSES, max_length=20)

    def __unicode__(self):
        return "Sandbox#%s from %s of %s" % (self.id, self.template, self.owner)

    def deploy(self):
        pass

    def destroy(self):
        pass

    def stop(self):
        pass

    def start(self):
        pass


class Template(models.Model):
    ans_playbook = models.CharField(max_length=50, blank=False)
    name = models.CharField(blank=False, max_length=30, help_text="POA/PBA versions information")
    note = models.TextField()

    def __unicode__(self):
        return "Template %s" % self.name

amp/taskapp/models.py
from django.db import models
from amp.sandbox.models import Sandbox


class AMPTask(models.Model):
    """
            Task for deploying VMs.
        Each VM deployed independently. Number of VMs depends on Template.
        Parent task - responsible for Sandbox deployment.
        Child tasks responsible for VMs deployment
    """
    task_id = models.CharField(blank=False, max_length=30)
    parent = models.ForeignKey("self", related_name="parent_task", null=True)
    sandbox = models.ForeignKey(Sandbox, related_name="task", null=True)

amp/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

amp/sandbox/views.py
from django.shortcuts import render
import models
# Create your views here.
from django.views.generic import ListView, View
from rest_framework import generics, permissions
from .models import Template, Sandbox, VM
from serializers import SandboxSerializer, VMSerializer



class SandboxListView(ListView):
    model = models.Sandbox
    context_object_name = "envs"
    template_name = "sandbox/dashboard.html"
    paginate_by = 6

    def get_queryset(self):
        qs = models.Sandbox.objects.filter(owner=self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super(SandboxListView, self).get_context_data(**kwargs)
        context['vm_templates'] = models.Template.objects.all()
        return context


class SandboxCreateView(View):
    template_name = "sandbox/dashboard.html"

    def get(self, request, *args, **kwargs):
        pass

    def post(self, request, *args, **kwargs):
        pass


class SandboxAPICreateView(generics.ListCreateAPIView):
    model = Sandbox
    serializer_class = SandboxSerializer
    permission_classes = [permissions.AllowAny]


class VMAPIListView(generics.ListAPIView):
    model = VM
    serializer_class = VMSerializer
    permission_classes = [permissions.AllowAny]


class VMAPIDetail(generics.RetrieveAPIView):
    model = VM
    serializer_class = VMSerializer

amp/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

amp/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}AMP{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">

        <!-- Your stuff: Third-party css libraries go here -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

        <!-- This file store project specific CSS -->
        <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block angular %}
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js"></script>
    {% endblock %}

</head>

<body>

<div class="m-b">
    <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">AMP</a>
            <button type="button" class="navbar-toggler hidden-sm-up pull-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
                &#9776;
            </button>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
                {% if request.user.is_authenticated %}
                    <ul class="nav navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#createModal">
                                <i class="fa fa-plus fa-lg"></i> Create Sandbox
                            </button>
                        </li>
                    </ul>
                {% endif %}

                <ul class="nav navbar-nav pull-right">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                        </li>
                        <li class="nav-item">
                            <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Log In" %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>

<div class="container">

    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}
    <div class="row margin-top-20">
        {% block content %}
            <p>Use this document as a way to quick start any new project.</p>
        {% endblock content %}
    </div>

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
    <!-- Latest JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>

    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->
    <script src="{% static 'js/project.js' %}"></script>
{% endblock javascript %}
</body>
</html>
 

amp/templates/pages/about.html
{% extends "base.html" %}

amp/templates/pages/home.html
{% extends "base.html" %}

amp/templates/sandbox/dashboard.html
{% extends "base.html" %}


{% block content %}
        {% for sb in envs %}
            {# first cycle prints  row, second- "", third -"" #}
            {% cycle "<div class='row margin-top-20'>" "" "" %}
            <div class="col-lg-4">
                <div class="card panel-primary">
                    <div class="card-header">
                        <i class="fa fa-server fa-fw"></i> {{ sb.name }} - {{ sb.template }}
                        <span class="pull-right text-muted small">
                            <ul class="nav">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#"
                                       role="button" aria-haspopup="true" aria-expanded="false">Action</a>

                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="#">Start</a>
                                        <a class="dropdown-item" href="#">Stop</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">Redeploy</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">Destroy</a>
                                    </div>
                                </li>
                            </ul>

                        </span>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-block">
                        <div class="list-group">
                            {% for vm in sb.vms.all %}

                                <a href="#vm_{{ vm.pk }}" class="list-group-item " data-toggle="collapse"
                                    aria-expanded="false" aria-controls="vm_{{ vm.pk }}" data-parent="#accordion">

                                    <i class="fa  fa-fw"></i>{{ vm.hostname }}
                                    <span class="pull-right text-muted small"><em>{{ vm.role }}</em>
                                    </span>

                                </a>

                                <div id="vm_{{ vm.pk }}" class="collapse">
                                    <ul class="list-group">
                                        <li class="list-group-item">
                                            <i class="fa fa-cogs fa-fw"></i> IP
                                            <span class="pull-right text-muted small">
                                                <em>{{ vm.ip_address }}</em>
                                            </span>
                                        </li>
                                        <li class="list-group-item">
                                            <i class="fa fa-user fa-fw"></i> Login: {{ vm.login }}
                                            <span class="pull-right text-muted small">
                                                <em>Pwd:  {{ vm.password }}</em>
                                            </span>
                                        </li>
                                    </ul>
                                </div>
                             {% endfor %}
                        </div>
                        <!-- /.list-group -->
                    </div>
                    <!-- /.card-block -->
                </div>
                <!-- /.card -->
            </div>
            {# every 3rd time close row element declared on the top cycle #}
            {% cycle "" "" "</div>" %}
             <!-- ./row -->
        {% endfor %}
{% endblock %}


{% block modal %}
    <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        <span class="sr-only">Close</span>
                    </button>
                    <h4 class="modal-title" id="createModalLabel">Create new Sandbox</h4>
                </div>
                <form action="{% url 'sandbox:create' %}" method="post">
                    <div class="modal-body">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name" class="control-label">Name</label>
                                <input type="text" class="form-control " id="name" name="name">
                            </div>
                            <div class="form-group">
                                <label for="template" class="control-label">Template:</label>
                                <select id="template" name="template" class="form-control">
                                    {% for tpl in vm_templates %}
                                        <option id="{{ tpl.pk }}"> {{ tpl.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

amp/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12 ">
    <a class="btn btn-primary" href="{% url 'users:update' %}">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

amp/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    <h1>{{ user.username }}</h1>
    <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn">Update</button>
          </div>
        </div>
    </form>
{% endblock %}

amp/templates/users/user_list.html
{% extends "base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

    <h2>Users</h2>

    <div class="list-group">
        {% for user in user_list %}
          <a href="{% url 'users:detail' user.username %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ user.username }}</h4>
          </a>
        {% endfor %}

    </div>

{% endblock content %}